listen_port = "8090"
interface_name = "tun0"
mtu = 1420
heartbeat_secs = 180
max_peers = 100
ipv6 = false
crypto_alg = "Aes256Gcm"
vpn_proxy = true
gateway = false
web = true
web_port = "8080"
ad_block = true
initial_peers = ["162.43.52.23"]
